import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {Engine} from '../src/engine.mjs';import {dispatch} from '../src/api.mjs';
class FakeAcp{constructor(config,handlers){this.handlers=handlers;this.closed=false;}async session({agentId}){return agentId||randomUUID();}async prompt(sessionId,text){this.handlers.onUpdate({sessionUpdate:'tool_call_update',content:[{type:'text',text:'large output'.repeat(10000)}]});return {message:'完成：证据已保存。',stopReason:'end_turn'};}async cancel(){}close(){this.closed=true;}}
const owner={operations:['*'],profiles:['personal','onward'],origins:['owner']};
async function complete(engine,id,run){for(let i=0;i<100;i++){const value=engine.get(id,run.id);if(value.status==='completed')return value;if(value.status==='failed')throw Error(value.error);await new Promise(r=>setTimeout(r,10));}throw Error('Not completed');}
test('independent profiles and sessions bound raw tool output while preserving complete event history',async t=>{const home=fs.mkdtempSync(path.join(os.tmpdir(),'moustachi-engine-'));const e=new Engine(home,{profiles:{personal:{persona:'Personal'},onward:{persona:'Onward'}}},{Acp:FakeAcp});t.after(async()=>{await e.close();fs.rmSync(home,{recursive:true,force:true});});e.start();const a=await complete(e,'personal',await dispatch(e,owner,{op:'submit',profileId:'personal',message:'first'}));const b=await complete(e,'personal',await dispatch(e,owner,{op:'submit',profileId:'personal',message:'second',taskId:a.task_id}));assert.notEqual(a.session_id,b.session_id);const inspector=await dispatch(e,owner,{op:'context',profileId:'personal',runId:b.id});assert.equal(inspector.lineage.length,2);assert(inspector.inspector.promptChars<10000);assert(e.profile('personal').store.all('SELECT * FROM events WHERE run_id=?',a.id)[0].data.length>100000);assert.equal(e.profile('onward').store.search('first').length,0);});
test('client scopes reject cross-profile access and forged feedback/owner origin',async t=>{const home=fs.mkdtempSync(path.join(os.tmpdir(),'moustachi-scope-'));const e=new Engine(home,{profiles:{personal:{},onward:{}}},{Acp:FakeAcp});t.after(async()=>{await e.close();fs.rmSync(home,{recursive:true,force:true});});const client={operations:['submit','get','history.search'],profiles:['onward'],origins:['feedback']};await assert.rejects(dispatch(e,client,{op:'history.search',profileId:'personal',query:'private'}),/Profile/);await assert.rejects(dispatch(e,client,{op:'submit',profileId:'onward',message:'change code',origin:'owner'}),/Origin/);});

class PermissionAcp extends FakeAcp {
 async prompt(){const response=await this.handlers.onPermission({sessionId:'fake',options:[{optionId:'allow',kind:'allow_once',name:'Allow once'},{optionId:'deny',kind:'reject_once',name:'Reject'}],toolCall:{toolCallId:'t',title:'Fixture approval only',kind:'execute'}});if(response.outcome.outcome==='cancelled')throw Object.assign(Error('Cancelled'),{cancelled:true});return {message:'explicitly approved',stopReason:'end_turn'};}
}
test('permission waits for explicit decision and cancellation resolves it',async t=>{
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'moustachi-permission-'));const e=new Engine(home,{profiles:{personal:{}}},{Acp:PermissionAcp});t.after(async()=>{await e.close();fs.rmSync(home,{recursive:true,force:true});});e.start();
 const a=e.submit({profileId:'personal',message:'fixture',channel:'test'});for(let i=0;i<100&&!e.permissions('personal').length;i++)await new Promise(r=>setTimeout(r,5));assert.equal(e.get('personal',a.id).status,'awaiting_permission');assert.throws(()=>e.resolvePermission('personal',e.permissions('personal')[0].id,'invented'),/advertised/);e.resolvePermission('personal',e.permissions('personal')[0].id,'allow');await complete(e,'personal',a);
 const b=e.submit({profileId:'personal',message:'second',channel:'test'});for(let i=0;i<100&&!e.permissions('personal').length;i++)await new Promise(r=>setTimeout(r,5));await e.cancel('personal',b.id);for(let i=0;i<100&&e.get('personal',b.id).status!=='cancelled';i++)await new Promise(r=>setTimeout(r,5));assert.equal(e.get('personal',b.id).status,'cancelled');assert.equal(e.permissions('personal').length,0);
});
class SlowSessionAcp extends FakeAcp {static prompts=0;async session(){await new Promise(r=>setTimeout(r,80));return 'slow';}async prompt(...args){SlowSessionAcp.prompts++;return super.prompt(...args);}}
test('cancel during setup prevents the model executing afterward',async t=>{const home=fs.mkdtempSync(path.join(os.tmpdir(),'moustachi-cancel-'));const e=new Engine(home,{profiles:{personal:{}}},{Acp:SlowSessionAcp});t.after(async()=>{await e.close();fs.rmSync(home,{recursive:true,force:true});});e.start();const run=e.submit({profileId:'personal',message:'cancel setup',channel:'test'});await new Promise(r=>setTimeout(r,20));await e.cancel('personal',run.id);await new Promise(r=>setTimeout(r,100));assert.equal(e.get('personal',run.id).status,'cancelled');assert.equal(SlowSessionAcp.prompts,0);});
