import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Store} from '../src/store.mjs';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moustachi-store-'));const store=new Store(dir);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return store;}
const request=(message,extra={})=>({profileId:'personal',origin:'owner',channel:'test',message,...extra});
test('profile databases isolate history, including 2-character Chinese and punctuation search',t=>{const a=setup(t),b=setup(t);a.message({channel:'test',role:'user',content:'邀请码已经发给测试者。Review project-alpha and C++ code.'});b.message({channel:'test',role:'user',content:'Personal only'});assert.equal(a.search('测试').length,1);assert.equal(a.search('邀请码').length,1);assert.equal(a.search('C++').length,1);assert.equal(b.search('邀请码').length,0);});
test('memory limits reject overflow atomically and ambiguous replacement cannot delete facts',t=>{const s=setup(t);s.memoryWrite({action:'add',content:'x'.repeat(2100),source:'user'});assert.throws(()=>s.memoryWrite({action:'add',content:'y'.repeat(120),source:'user'}),/capacity/);assert.equal(s.memorySnapshot().memory.length,2100);s.memoryWrite({target:'user',action:'add',content:'Paris finance',source:'user'});s.memoryWrite({target:'user',action:'add',content:'Paris coding',source:'user'});assert.throws(()=>s.memoryWrite({target:'user',action:'replace',oldText:'Paris',content:'Other',source:'user'}),/ambiguous/);});
test('idempotency is scoped by channel, new task default, quoted reply restores explicit task',t=>{const s=setup(t);const a=s.submit(request('one',{externalId:'a'}));assert.equal(s.submit(request('one',{externalId:'a'})).id,a.id);const b=s.submit(request('two'));assert.notEqual(a.task_id,b.task_id);s.bind('test','outgoing-1',a.task_id);assert.equal(s.submit(request('continue',{replyTo:'outgoing-1'})).task_id,a.task_id);});
test('working session rotates without losing history and freezes its memory snapshot',t=>{const s=setup(t),run=s.submit(request('first'));let session=s.chooseSession(run.task_id,{memory:'first'},{maxTurns:1});const reused=s.chooseSession(run.task_id,{memory:'second'},{maxTurns:1});assert.equal(reused.snapshot.memory,'first');s.exec('UPDATE sessions SET turns=1 WHERE id=?',session.id);const next=s.chooseSession(run.task_id,{memory:'second'},{maxTurns:1});assert.notEqual(next.id,session.id);assert.equal(next.parent_id,session.id);assert.equal(s.search('first').length,1);});
test('restart marks in-flight work interrupted, never automatically repeats mutations',t=>{const s=setup(t);const r=s.submit(request('mutate'));s.exec("UPDATE runs SET status='running' WHERE id=?",r.id);s.recover();assert.equal(s.run(r.id).status,'interrupted');});
test('skills require distinct completed-task evidence; pinned skills are never auto-archived',t=>{const s=setup(t);s.skillCreate({id:'candidate',description:'reusable',content:'Instructions'});s.skillCreate({id:'pinned',description:'pinned',content:'Keep',pinned:true});const a=s.submit(request('a')),b=s.submit(request('b'));assert.throws(()=>s.skillReport({id:'candidate',runId:a.id,evidence:'checked'}),/completed/);s.complete(a.id,'done',{});s.complete(b.id,'done',{});assert.equal(s.skillReport({id:'candidate',runId:a.id,evidence:'test output'}).state,'candidate');assert.equal(s.skillReport({id:'candidate',runId:a.id,evidence:'same task'}).successfulDistinctTasks,1);assert.equal(s.skillReport({id:'candidate',runId:b.id,evidence:'second test output'}).state,'active');const report=s.curate({dryRun:false,now:Date.now()+31*86400000});assert.equal(report.changes.length,1);assert.equal(s.one('SELECT state FROM skills WHERE id=?','pinned').state,'active');});

test('changed authorization origin rotates working context',t=>{const s=setup(t),run=s.submit(request('first'));const a=s.chooseSession(run.task_id,{origin:'feedback'});const b=s.chooseSession(run.task_id,{origin:'owner'});assert.notEqual(a.id,b.id);assert.equal(b.parent_id,a.id);});
